name: beauty-clinic-pos
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - tk
  - pillow
  - reportlab
  - sqlite
  - bcrypt
  - python-dotenv
  - sqlalchemy
  - pandas
  - numpy
  - pip:
    - -r requirements.txt
